### ISSUE TITLE
WARNING: NN Message inbox overflow!

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#106]
E:\FL\Scratch\Source\Client\nn\NN_Messaging.cpp(162) : *** WARNING: NN Message inbox overflow!

**Comment by thaddeus-ex** [comment]
Isnt this down to missing naicknames for "anomaly-detected" etc from NNVoice

**Comment by erikroe** [comment]
Maybe it is fixed now. I added the nnvoice stuff from FLHDE which fixed a few missing sounds by just adding empty ones.
