### ISSUE TITLE
Update SUR file on BR Destroyer for new turrets

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#224]
Update SUR file on BR Destroyer for new turrets

**Comment by thaddeus-ex** [comment]
[BR_DESTROYER.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/10690075/BR_DESTROYER.zip)

Holes sealed in Br_frnt_bdy_top_lod1. HPs added HPCM01, HpTorpedo01, HpShield01, HpPilot, HpReactor. Missile battery HPs BM01 & BM02 returned to model in default postion. 

Sur rebuilt, completely new. Added HpTurret_B4_03 through 06. Corrected original HpTurret_BM_01 & 02. Sur shell added for HpShield02 in default position. HpShield01 Created & HpTorpedo01 & HpCM01 in Discovery Postition.
