### ISSUE TITLE
Apply multiboxing patch

### ISSUE THREAD

**Issue by BC46** [Freelancer-Sirius-Revival/FLSR#243]
```
Freelancer.exe. Base: Default No-CD EXE
1E6DCC: AnsiChar / char8_t 'F' -> ''. Breaks the CreateMutex IpName, allowing multiple instances of Freelancer to run simultaneously. 
```
This'll allow players to open multiple instances of FL:SR so they can transfer cargo between their accounts without needing another player, etc.

**Comment by erikroe** [comment]
Was closed via the duplicate https://github.com/Freelancer-Sirius-Revival/FLSR/issues/281
