### ISSUE TITLE
Clean up textures and add bay doors Li_cruiser 

### ISSUE THREAD

**Issue by thaddeus-ex** [Freelancer-Sirius-Revival/FLSR#249]
Clean up textures on rear apron and around starboard star motif. Install baydoors in intended position. Add CM and Mine HPs with surs. Check SUR for missing parts

**Comment by erikroe** [comment]
Found on the bottom something else 
![grafik](https://user-images.githubusercontent.com/48999656/227791483-20952a89-4e19-4bac-86eb-a16933759675.png)

**Comment by thaddeus-ex** [comment]
I can quite categorically say that this ship in particular is the worst piece of badly textured nastiness in the game. those grey squares there are "just not textured at all", not even attempted. Its a Friday nighter, its like they were told theyre all fired on monday next and try and finish what projects they had in the time left - and this is the result. This isnt even 5% of the stuff I have already done on this ship. And that is my critique of the li_cruiser. Let us not speak of its dreadfulness till the revised version is up and you point out stuff I've missed.

**Comment by thaddeus-ex** [comment]
section of revised model, textures are of course original, not hd.  ![li_cruiser_revision01](https://user-images.githubusercontent.com/92892138/227805681-6cb766e4-51cf-418b-9efc-ebfb9658f283.jpg)
