### ISSUE TITLE
Make Fighter Classes more distinctive in their roles

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#272]
VHFs could be made more tanky: Slower, but far more armor and shield.
Lights already lack the firepower but have good manouverability. Probably good as they are.
Mediums are probably good too? Do they conflict with the Lights?
What about the exception of the Starfliers Very Light ships?

**Comment by FireFlyEx** [comment]
Your scale is a bit off.. isn't it?

**Hybrid:**
Maneuverability: C
Mass: _C_
Armor: A
Strafing: _C_

**VHF:**
Maneuverability: D
Mass: _D_
Armor: S
Strafing: _D_

Plus now we have variants coming, so these should also be different for that.
