### ISSUE TITLE
Gas Mining, Loot via downed shield on object

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#290]
I would like to introduce a different way of mining, Gas pockets weill become an mineable but not destroyable object with a shield that only can be damage by a special type of gun. 

The Gas pocket will be outfited with a special shield that has a long reload time but will reload to 100%. every time the shield goes to 0 the gas pocket will drop the commodity it represents. 

The special gas mining equipment will be an X Slot gun.

**Comment by FireFlyEx** [comment]
https://github.com/Freelancer-Sirius-Revival/FLSR/issues/596
