### ISSUE TITLE
5 first Cloaking devices 

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#300]
Custom Cloak Device 
- Out of Wrackage 

4 House Cloaking Devices

**Comment by erikroe** [comment]
Fighter = 2 Min
Freighter = 3 Min
Gunboat = 4 Minu
Cruiser / Destroyer = 5 Min
Battleship = 10 Min

For now at secret shipyards and wrecks.
