### ISSUE TITLE
Omega-3 Wilkes Field wrong infocard text

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#304]
![grafik](https://user-images.githubusercontent.com/48999656/212486858-08481405-f5e3-466a-99a8-90751cafb4ef.png)
Speaks of Red Hessians, but they never get out here.

**Comment by FireFlyEx** [comment]
Since you guys are obsessed with following the lore.. why wouldn't you bring it back?

**Comment by erikroe** [comment]
We want to return it back to vanilla FL.

**Comment by erikroe** [comment]
Hessians will be brought back via NPC rebalance. Closing this now.
