### ISSUE TITLE
Check Red Hessian patrol routes leading to and inside of Omega 3 and 41

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#316]
In standard FL there is Red Hessians in Omega 3. But in our mod it is not. Why? And should it be brought back?
Has to do with https://github.com/Freelancer-Sirius-Revival/FLSR/issues/304

**Comment by erikroe** [comment]
I have removed those Hessians myself ages ago. For O-3 they were brought back now. O-41 must be checked.

**Comment by Caenen** [comment]
Sarge fixed both Omega-3's and Omega-41's routes in path 2024.5.
