### ISSUE TITLE
Change power plants for NPCs to be drainable via Energy Weapons

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#32]
NPCs use infinity power generators. This makes the usage of energy-draining weapons entirely useless. They may get special generators that leaves the AI room to shoot at will, but also be disruptable by energy weapons.

**Comment by FireFlyEx** [comment]
You can't have energy drain and free shooting with the same equipment players are using? What exactly do you want to be disrupted by allowing this?

**Comment by erikroe** [comment]
AI cannot work with depleting energy and managing this properly really. So NPCs running out energy will make them constantly shoot only as much as it works. Crippling them basically by their own inability.
