### ISSUE TITLE
Include medium Transport

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#321]
@thaddeus-ex prepared a Medium Transport model that however still needs some refinement. If that ship is any use for players or not needs to be seen. Though it can be put in the game anyway for NPCs at least.

**Comment by thaddeus-ex** [comment]
[TRANSPORT_MEDIUM.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/10690123/TRANSPORT_MEDIUM.zip)

Corrected SURs
