### ISSUE TITLE
Cloaking Device Equip Models

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#356]
Cloaking devices are visible in space. A fitting representation are the Hardware co_stealth 1, 2 and ku_stealth 3 models in `equipment/models/hardware`
The stealth 1 works good for Fighters if scaled down to 65%
The stealth 2 should be fine for Gunboats or Cruisers
The stealth 3  should be good for Battleships or Liners.

They need some SURs. At best a copy made of them in ST Equip directory with names like "cloaking_device01" and counting.

**Comment by thaddeus-ex** [comment]
[HARDWARE.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/10710468/HARDWARE.zip)

HpConnect added to each model, Stealth1 reduced to 60%. Suggest keeping both models as Stealth1 maybe used as deck/shop model, sur added to each model
