### ISSUE TITLE
Mine Dropper on CSV

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#360]
Mine Dropper on CSV

**Comment by thaddeus-ex** [comment]
probably best on a pad directly below the rear turret

**Comment by erikroe** [comment]
Or switching Thruster to there, and Mine Dropper where the Thruster is. For a symmetry of CM and Mine.

**Comment by thaddeus-ex** [comment]
> Or switching Thruster to there, and Mine Dropper where the Thruster is. For a symmetry of CM and Mine.

probably best solution.

**Comment by thaddeus-ex** [comment]
thruster pad complete

![h_csv](https://user-images.githubusercontent.com/92892138/227747278-3204351c-2d1f-457c-b9c7-05eb34f98090.jpg)

currently three options for CM/Mine postions:- current thruster position above weapons on angled plate, on the flat area above that, or, my preferred spot on the tail/root section just ahead of the engines

![h_csv_1](https://user-images.githubusercontent.com/92892138/227747332-c18aeecd-b986-4eaa-aa40-d27c30337d1b.jpg)

**Comment by erikroe** [comment]
I like your preferred position, too.

**Comment by thaddeus-ex** [comment]
![csv_lod0_rev01](https://user-images.githubusercontent.com/92892138/230684838-971c9d8a-4d09-4343-b59d-cfada0951f17.jpg)

55 smoothing groups later, colours corrected for Junker version (still pink) - its easier to just recolour in .xml at least for me. Intergrated CM and mine points. More HP pads added for interest - it is a utility vehicle afterall. Some interest added to the cockpit. 2nd-man chair added, floor made less flat and boring and a door added to the back bulkhead.

**Comment by thaddeus-ex** [comment]
![screen32](https://user-images.githubusercontent.com/92892138/230726298-6cad3daa-e0ff-4284-8a24-d36f1b59e929.jpg)

Revised position for CM, Mines & Thruster. Hit boxes added on new Hp pads as well as Radar01. HpWeapon03-04 and HpTorpedo01-02 added and hitboxed
Revised cockpit arrangement
SUR revised to current Lithium version. Shield sur updated.
Hud wireframe revised and updated
u_glass added to utility_ships.mat
u_glass HighGlassMaterial entry added to dacom.ini
