### ISSUE TITLE
Entrypoint D3DKMTMakeResident not found in GDI32.dll

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#363]
OS: Windows 7 Pro

**_The game will not run for me. After giving a series of errors for missing files, which I downloaded and added, it finally got stuck on the following:_**

Popup error: The procedure entry point D3DKMTMakeResident could not be located in the dynamic link library GDI32.dll

**The client log ended here when the error popped up:**

C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(1111) : NOTICE:General:Current DACOM.DLL version: 1.11.173
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(1112) : NOTICE:General: Compiled against version: 1.11.173
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(852) : NOTICE:General:DACOM: initialize: dllpath: 'E:\Projects\FLSR\EXE'
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(880) : NOTICE:General:DACOM: initialize: Loading DLL's from [Libraries] group.
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(618) : NOTICE:General:DACOM: AddLibrary: DLL 'E:\Projects\FLSR\EXE\ReadFile.dll' [1.11.173]
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(618) : NOTICE:General:DACOM: AddLibrary: DLL 'E:\Projects\FLSR\EXE\x86math.dll' [1.11.173]
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(618) : NOTICE:General:DACOM: AddLibrary: DLL 'E:\Projects\FLSR\EXE\EngBase.dll' [1.11.173]
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(618) : NOTICE:General:DACOM: AddLibrary: DLL 'E:\Projects\FLSR\EXE\system.dll' [1.11.173]

**These log entries pop up after closing the popup:**

C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(612) : ERROR:General:DACOM: AddLibrary: unable to load dll 'RP8.dll', ignoring...
C:\work\builds\dalibs\dalibs-build\build\Src\DACOM\Dacom.cpp(612) : ERROR:General:DACOM: AddLibrary: unable to load dll 'Autoconnect.dll', ignoring...
C:\work\builds\dalibs\dalibs-build\build\Src\System\SysContainer.cpp(291) : NOTICE:General:SystemContainer: LoadSystemComponents: Loading 'DirectX8' [] returned [FAILED]
C:\work\builds\dalibs\dalibs-build\build\Src\Alchemy\Alchemy.cpp(117) : ERROR:General:Alchemy: init: unable to acquire IID_IRenderPipeline

**Windows Event 1000, Application Error report:**

Faulting application name: Freelancer.exe, version: 1.0.1223.11, time stamp: 0x00534d69
Faulting module name: alchemy.dll, version: 1.11.0.173, time stamp: 0x3e401cd3
Exception code: 0xc0000005
Fault offset: 0x000011d2
Faulting process id: 0x810
Faulting application start time: 0x01d93ec6d1186c09
Faulting application path: E:\Projects\FLSR\EXE\Freelancer.exe
Faulting module path: E:\Projects\FLSR\EXE\alchemy.dll
Report Id: 8448e21f-aabd-11ed-b6f7-d05099076c2c

**Dependencies output for freelancer.exe:**

https://pastebin.com/zq26a8K0

**Comment by erikroe** [comment]
@FireFlyEx Can you try if it works if you remove your d3d8.dll in the Freelancer\EXE directory?

**Comment by FireFlyEx** [comment]
I have confirmed that this is a result of a copy of d3d8.dll that is not compatible with Windows 7 or 8. Recommend ENBSeries version for DX8 to DX9. Also allows fine tuning of special effects through the ini file.
