### ISSUE TITLE
Look at the Log Yo! Errowrs

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#365]
Not that you haven't seen them already but there are a bunch of errors in the log file. And this is just from playing in the start system.

I removed most of the duplicates.

E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Br_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ku_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Br_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Li_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Rh_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Br_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Ku_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Ku_base_rock_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Li_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Rh_large_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Iw_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Om_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Ta_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Si_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(Oc_Proxy_Li_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Br_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Ku_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Li_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Rh_base_rock_large_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Rh_small_station_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Liner_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Rh_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Ku_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Br_Battleship_Base) failed.
E:\FL\Scratch\Source\Common\Systems.cpp(3071) : *** WARNING: get_base(No_Proxy_Li_Battleship_Base) failed.

E:\FL\Scratch\Source\Client\LoginMgr.cpp(351) : NOTICE:General:Starting single player game.
E:\FL\Scratch\Source\Client\Gf\LocationController.cpp(1029) : *** WARNING: Failed to get start location

C:\work\builds\dalibs\DALIBS~1\build\include\IMaterialImpl.h(575) : NOTICE:General:texture verify failed: mv_vidmaterial: vidmaterial.tga
E:\FL\Scratch\Source\Client\Space\CliAsteroid.cpp(209) : *** WARNING: Asteroid field (solar\rings\herschel_ast.ini) hooked up to zone (Zone_start_Herschel_ring_asteroids) which is not a valid shape

E:\FL\Scratch\Source\Client\space\StarSys.cpp(716) : *** WARNING: Voice message 2353493514 is invalid for voice 3073825485
E:\FL\Scratch\Source\Client\space\StarSys.cpp(716) : *** WARNING: Voice message 2351700488 is invalid for voice 3073825485

E:\FL\Scratch\Source\Common\Archetype.cpp(60) : *** ERROR: ArchDB::Get(0) failed

E:\FL\Scratch\Source\Client\LoginMgr.cpp(351) : NOTICE:General:Starting single player game.
E:\FL\Scratch\Source\Client\Gf\LocationController.cpp(1029) : *** WARNING: Failed to get start location
E:\FL\Scratch\Source\DALib\DALib.cpp(376) : WARNING:General:******* DA SYSTEM: trailing references *******
E:\FL\Scratch\Source\DALib\DALib.cpp(376) : WARNING:General:******* DA SYSTEM: trailing references *******

**Comment by erikroe** [comment]
Duplicate with https://github.com/Freelancer-Sirius-Revival/FLSR/issues/252 and https://github.com/Freelancer-Sirius-Revival/FLSR/issues/98
