### ISSUE TITLE
Set up right interior for Buffalo

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#382]
Buffalo is a Liberty base but uses Bretonia interior

**Comment by FireFlyEx** [comment]
Deck and Deck2 are the only ones that have Bretonia interiors and ironically they are almost exactly the same as the rest of the base, only there are 2 weird statues in the BR one. Will need to visually find which file matches the interior from Liberty.

**Comment by FireFlyEx** [comment]
Fixed all of the interiors but I have one error left. Will need to edit the actual thn file for this one..

```E:\FL\Scratch\Source\Client\GF\ScriptLight.cpp(375) : *** WARNING: invalid light reference to name Ambi_Lightning_ALL_LtG23_Trgt```

**Comment by erikroe** [comment]
I know. Usually I defined the interiors only by location on the map or by faction that logically built it. And for Krüger and Daumann it would be always a Rheinland interior for example.

**Comment by FireFlyEx** [comment]
And what about all of the IW, EW, and BW systems that use li_09?

**Comment by erikroe** [comment]
I think the li09 is like kind of a "neutral" base interior because Liberty interiors afaik do not have any symbolism. Unlike the Bretonia or RH one with each their emblems on deck.

**Comment by FireFlyEx** [comment]
I checked the **li_09_bar_ambi_li01_12.thn** file and it looks like you actually added the broken light: **Ambi_Lightning_ALL_LtG23_Trgt**. Why did you do that?

**Comment by erikroe** [comment]
This file is not part of the repo, so I sure did not do anything there.
