### ISSUE TITLE
WARNING: Failed to get start location

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#393]
*** WARNING: Failed to get start location
This may be caused by a broken Room setup.
In worst case this MIGHT have to do with the mission bug for whatever reasons. http://www.voidserver.com/modules.php?name=Forums&file=viewtopic&p=192867

**Comment by BC46** [comment]
Freelancer always spews this line when starting the game, even in vanilla. If you want to get rid of it, your best bet would probably be to look at the assembly to see how it can be suppressed.

**Comment by erikroe** [comment]
With that I think we can just ignore it and keep it as it is.
