### ISSUE TITLE
SpewSpam Ainu -> Eqip Dude

### ISSUE THREAD

**Issue by Nekura** [Freelancer-Sirius-Revival/FLSR#398]
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: Eye IK Right) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: BLIP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: ROLP, child: B_Right Outer Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: ROBR, child: B_Right Outer Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RMBR, child: B_Right Middle Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RICH, child: B_Right Inner Cheek) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RIBR, child: B_Right Inner Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RBLP, child: B_Right Bottom Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RBEY, child: B_Right Bottom Eye) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LOLP, child: B_Left Outter Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LOBR, child: B_Left Outer Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LMBR, child: B_Left Middle Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LICH, child: B_Left Inner Cheek) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LIBR, child: B_Left Inner Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LBLP, child: B_Left Bottom Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LBEY, child: B_Left Bottom Eye) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: CHIN, child: B_Chin) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: BLIP, child: B_Bottom Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Root, child: Head) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head, child: Head01) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: ROLP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_Left EyeLid) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: ROBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: RMBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: RICH) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: RIBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: RBLP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: RBEY) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_Left Top Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_Right EyeLid) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LOLP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LOBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LMBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LICH) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LIBR) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LBLP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_Right Top Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 1A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 1B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 2A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 2B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 3A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 3B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 4A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 4B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 5A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 5B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 6A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 6B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 7A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 7B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 8A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 8B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 9A) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_SplineBone 9B) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: B_Top Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: LBEY) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: CHIN) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: Eye IK Left) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: Eye IK Right) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: Head01, child: BLIP) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: ROLP, child: B_Right Outer Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: ROBR, child: B_Right Outer Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RMBR, child: B_Right Middle Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RICH, child: B_Right Inner Cheek) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RIBR, child: B_Right Inner Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RBLP, child: B_Right Bottom Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: RBEY, child: B_Right Bottom Eye) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LOLP, child: B_Left Outter Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LOBR, child: B_Left Outer Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LMBR, child: B_Left Middle Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LICH, child: B_Left Inner Cheek) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LIBR, child: B_Left Inner Brow) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LBLP, child: B_Left Bottom Lip) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: LBEY, child: B_Left Bottom Eye) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: CHIN, child: B_Chin) channel.
C:\work\builds\dalibs\dalibs-build\build\Src\EngBase\Anim\Anim.cpp(757) : WARNING:General:Sc_MLHEAD_MOTION_SHAKHEAD_NO_000LV_XA_% failed to map JOINT (parent: BLIP, child: B_Bottom Lip) channel.

**Comment by thaddeus-ex** [comment]
isnt this down to the robots not having separate heads. adoxa rewrote the trader thn script for the robots removing the head parts, more info -  https://the-starport.net/modules/newbb/viewtopic.php?topic_id=3653&forum=27&post_id=37997#forumpost37997
