### ISSUE TITLE
Remaster Freelancer music in better quality

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#404]
The Freelancer soundtracks in the game are of quite low quality. The bonus CD contains all tracks in high quality. These however are not properly looped to fit the actual needs for the game. So they must be cut and looped properly.
This does not just benefit us but also Freelancer HD project.

**Comment by erikroe** [comment]
https://github.com/Freelancer-Sirius-Revival/FLSR/issues/11 shows we need to do this ourselves.

**Comment by Worldwave** [comment]
On it

**Comment by Worldwave** [comment]
Liberty, Bretonia, Tau completed

**Comment by Worldwave** [comment]
Rheinland, Kusari completed

**Comment by Worldwave** [comment]
Independent Worlds, Omega, Omicron, Sigma, Nomads completed
