### ISSUE TITLE
Correct textures on end caps of space_factory02.cmp

### ISSUE THREAD

**Issue by thaddeus-ex** [Freelancer-Sirius-Revival/FLSR#407]
textures bably distorted on end cap of starboard acc. module - affects lod0 & lod1. correct and re-export.

**Comment by thaddeus-ex** [comment]
[space_factory02.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/10832370/space_factory02.zip)
Textures corrected on end caps, new wireframe from root_lod1. lights either side of dock bay on approach moved to outside of structure. visually checked as working but orientation not checked..

**Comment by FireFlyEx** [comment]
I just submitted a PR of this file with hardpoint edits. Need to make sure these are reconciled. Why was this attached instead of done as a PR?
