### ISSUE TITLE
Wreck for Krüger station Richthofen in Sigma-13

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#42]
From a NPC text: Station Richthofen of Krüger in Sigma-13.

**Comment by thaddeus-ex** [comment]
![screen5](https://user-images.githubusercontent.com/92892138/219955351-55e2114a-09c8-4502-afbe-f1a9137f7598.jpg)

with the "Old Kruger storage container"

**Comment by erikroe** [comment]
True. It should at least be named Richthofen I'd say.
