### ISSUE TITLE
Drag Modifier support

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#422]
`74-->EB | common.dll | 053796 | adoxa | adjust cruise speed according to drag_modifier`
`057B-->4174 | common.dll | 0DAD24 | adoxa | make drag_modifier independent of interference/damage`

**Comment by FireFlyEx** [comment]
This is currently only being used by one asteroid field in Tau-23, which probably means that it's dead code that wasn't deleted. What are you planning to do with it?

**Comment by erikroe** [comment]
It is not dead code, it actually works. I want to restore the feature a bit more with the hacks above to later on use it around nebulas on demand. For that we need additional planning however.

**Comment by FireFlyEx** [comment]
I meant dead as in they changed their mind on using it. It could maybe make certain nebulae a little more interesting. How about this idea... in that Tau system that's kinda useless... make a new race track and add hidden little zones with the drag modifier set to boost your speed to make races more interesting?

**Comment by erikroe** [comment]
Closed as we simply don't need this currently..
