### ISSUE TITLE
Buff Nomad capital ships to be threats to colony-capships

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#432]
Currently Nomad capital ships (cruiser and both battleships) are not very frightening against colony-battleships and cruisers. The Nomad ships die too fast with colony-main batteries. And their own damage on colony ships is not enough. It's basically no threat at all to any colony ship. This must be fixed by probably changing the hitpoints of bigger Nomad capships, buffing their heavy main weapons, and their AI possibly, too.

**Comment by Worldwave** [comment]
Sharing my thoughts that capships might be better off with guns that slam for more damage but have such a low turn-rate that they must have support from smaller ships in a true fleet. This would apply to all capships and not only nomads. That way you get a food chain of fighter > bomber > capship > station/other capship

Prompts me to ask - do cruiser/battleship main guns have gimbals?

**Comment by erikroe** [comment]
Capital ship main guns are already extremely so. So slow that a battleship cannot fight gunboats anymore at times.
