### ISSUE TITLE
Base weapons disrupt tradelanes

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#436]
Tradelane and base weapons can disrupt tradelanes. Most notable example: Planet New London where the lanes are far too close to the planet. Should consider removing 1 ring from each lane and moving the other bases further back.

**Comment by FireFlyEx** [comment]
Suggested fix is to make a new weapon type that does almost zero damage (0.000001) to solars. Means adding a new matching type of shield.

**Comment by erikroe** [comment]
I like the idea of an TLR Shield Type the most. Any of the new station weapons (they are used exclusively, no old guns) need to have a Weapon Type that does 0 damage on the TLR shield. Other weapons must do 1.
