### ISSUE TITLE
Adding updated model of ku_auto_blaster model

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#449]
![2023-03-11 23_39_23-HardCMP _ D__Daten_Modding_Freelancer_Modding_DATA_EQUIPMENT_MODELS_WEAPONS_ku_a](https://user-images.githubusercontent.com/24990509/224514569-62442adc-5a38-4de5-9b64-5edd95bbfdd3.png)

**Comment by erikroe** [comment]
Was merged with all weapons updated and plenty new designs from Thaddeus' mod.
