### ISSUE TITLE
Shields have strange Reload behaviour

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#456]
Is there a calculation how much capacity shields have after the shield comes back online?

Depending on the Shield it has 75% or less. 

Outlander for example reboots with 75% while the Skull Shield just has 50%.

**Comment by FireFlyEx** [comment]
How are you getting this information?

**Comment by XxSARGExX** [comment]
have tested it with caenen and also saw it on a stream by worldwave as well as testes myself on a second account. 

if i take down a Skull shield with the same gun as i take down the Outlander shield. Both will always have different capacity stat after restart

**Comment by FireFlyEx** [comment]
But is it consistent? Does the Skull always rebuild the same amount and Outlander likewise?

**Comment by Caenen** [comment]
I need to run the test with more scrutiny again; I believe it's the base shield regen or extraslot shield regen module that causes it to restore at a certain shield amount. That's an easy test whenever there's an opportune time in the next couple of days.
