### ISSUE TITLE
Crosshair calculation for thrusting npc´s is strange

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#457]
We always know that the crosshair  is calculated by the projectile speeds of your ACTIVATED guns. 

We noticed somethin weird If Npc´s using thrusters and with specific weapons your guns will always fire far behind. Hitting Thrusting NPCs is almost impossible even if they just fly straight. 

Example: ATRAX against higher level Corsairs.

We need to change something about that. because especially with slow guns it is not fun .

**Comment by FireFlyEx** [comment]
Can we disable the force-auto-aim? It would still show the firing target but you can actually fire where you are aiming.

**Comment by Worldwave** [comment]
The problem with disabling force-auto-aim is your weapon's zeroing (the point where all projectiles from different origin points converge) changes to some far away point when you are not aim-locked, preventing your projectiles from converging on your target. Can we make it smooth so it changes the zeroing when aiming at the reticle without locking guns?
