### ISSUE TITLE
More distinctive pilots behaviour

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#46]
Piloten Verhalten & Formationen  (Aktuelle Idee) : 

Formationen 
Unorganisiert = Offener / Evtl. gemischte Piloten 
Organisiert = Standard Formationen 
Militär = Abfangformationen oder Defensiv Formationen / gleiche Piloten
Polizei = Standard Formationen / Evtl. gemischte Piloten
Kopfgeldjäger = Verschiedene Formationen / Verschiedene Piloten 
Korsaren = Abfangformationen oder Defensiv Formationen / gleiche Piloten 
Ausgestoßene = Offene Formation / starke verschiedene Piloten 
Wegelagerer = Überfall Formationen 
Firmen = Defensive Formationen / verschiedene Piloten 

Verhalten 
Piraten = Aggressiv / Ungenau / Wenig Defensiv 
Organisiert = Taktisch / Genau / normal Defensiv
Militär = Taktisch / Treffsicher / gute Abwehrmanöver 
Polizei = Taktisch / Genau / normal Defensiv 
Kopfgeldjäger = Zufällig je nach Pilot (alles dabei)
Korsaren = Taktisch / Treffsicher / normal Defensiv 
Ausgestoßene = Aggressiv / Genau / gute Abwehrmanöver 
Wegelagerer = Taktisch / Genau / normal Defensiv 
Firmen = Je nach Firma verschiedene Piloten (Lore)

**Comment by FireFlyEx** [comment]
Pilot Behavior & Formations (Current Idea) :

Formations
Disorganized = Open / Possibly mixed pilots
Organized = Standard formations
Military = Intercept formations or Defensive formations / Same pilots
Police = Standard formations / Possibly mixed pilots
Bounty Hunter = Different formations / Different pilots
Corsairs = Interception formations or Defensive formations / Same pilots
Outcasts = Open formation / Strong miscellaneous pilots
Highwaymen = Raid formations
Companies = Defensive formations / Different pilots

Behave
Pirates = Aggressive / Inaccurate / Low defense
Organized = Tactical / Accurate / Normal defensive
Military = Tactical / Accurate / Good defensive maneuvers
Police = Tactical / Accurate / Normal defensive
Bounty Hunter = Random depending on pilot (all included)
Corsairs = Tactical / Accurate / Normal defense
Outcasts = Aggressive / Accurate / Good defensive maneuvers
Highwayman = Tactical / Accurate / Normal defensive
Companies = Depending on the company, different pilots (Lore)
