### ISSUE TITLE
Empty rumour on Pacifica

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#478]
![grafik](https://user-images.githubusercontent.com/48999656/226112716-1c98844d-dc8d-4ed2-9103-39f5fa3731b7.png)

**Comment by thaddeus-ex** [comment]
rumours run inclusively from 131460-131470 on iw0101, cant see a problem in mbases, maybe dll related

**Comment by erikroe** [comment]
It was indeed empty. On FLHDE they removed it from mbases.
