### ISSUE TITLE
Improved Starflier-series models

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#488]
Improved Starflier-series models.
![grafik](https://user-images.githubusercontent.com/48999656/226114510-36aa049e-c4c9-4734-aa89-f3bbab324049.png)

**Comment by thaddeus-ex** [comment]
Also the possibility of another ship no one asked for - twin engined Starflier with same whiskers and weapon mounts as Blazer. "Kicker" project.
