### ISSUE TITLE
Docking on bases sometimes crashes game

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#496]
It happens randomly.
The only spew error we got directly at a crash so far:
`E:\FL\Scratch\Source\Client\Gf\LocationController.cpp(256) : *** ERROR: Could not find base id -65536`

**Comment by FireFlyEx** [comment]
I can't re-create this crash. Please give more information.

**Comment by erikroe** [comment]
Apparently this is a general error happening on multiple stations. Client-side issue as it seems. Happened when many players were on the server. Or the server sent wrong packages to the client. Hard to reproduce.

**Comment by FireFlyEx** [comment]
Was it all players or specific ones flying specific types of ships?

**Comment by erikroe** [comment]
Fixed by new FL Hook version.
