### ISSUE TITLE
Planetscapes ambient ships spawn and end locations are not off-screen for some resolutions

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#499]
On some planets (e.g. Crete), the ambient ship spawns and despawns happen on screen at resolutions such as 2560x1440p. That's because both the spawn locations and the movement destinations end up within the screen edges. Ships that reach the end of their trajectory stand still at the location until they despawn.

This can happen in addition to the already noted issue where the static models themselves do not connect beyond the edges of the screen.

**Comment by erikroe** [comment]
@Caenen Is this still the case with the 16:9 planet-side scripts now?

**Comment by Caenen** [comment]
Luckily I still have an older installation of the mod so I could compare directly. All of the planets where I noticed the ships despawning on screen (Stuttgart, Crete) have this fixed now. Additionally, the edges of planetscape models are no longer visible on screen. Stuttgart for example:

Before 
![Stuttgart pre](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/345a26d8-2f88-4d1c-b390-b6bc9b19cefd)

Now
![Stuttgart post](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/f4dfa08f-ede8-447f-a799-85329cd0f256)

In turn however, the top and bottom of the normal planetscape view is cut off now, which may be worse on some planets than other ones. The landing deck on Stuttgart is largely cut off (see above) and the lights on top of the Liberty are no longer on screen for example:

Before
![Manhattan pre](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/4662a520-b826-4026-a3de-1a2ac4baeaae)

Now
![Manhattan post](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/44a9be32-345a-4455-84f0-c98c27046b5c)

This is probably an acceptable tradeoff unless you already know another fix for that, so I'll leave it to you to open a new issue if you see fit.
