### ISSUE TITLE
Decrease size of Zone 21 to be less over the top

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#5]
Decrease size of Zone 21 to be less over the top.

**Comment by FireFlyEx** [comment]
What's the goal here? It can be reduced by a little or a lot, but what are you hoping for by reducing it?

**Comment by erikroe** [comment]
Just to make it not be completely over the top to fulfill it's goal and have hundreds of thousands of mines in large areas for no good reason. A 10km radius sphere would be enough.

**Comment by FireFlyEx** [comment]
What do you want instead? Just a lot of empty space or something else?

**Comment by erikroe** [comment]
Yes in that case it would just give way to a lot of empty space. I just dislike how Zone 21 is completely oversized for its purpose. The jumpgate and the access lane can stay where they are. But the inner exclusion zone can be shrinked down a lot to only be big enough for the gate, maybe a bit of defense platforms/BS around, and then that's it already.
