### ISSUE TITLE
Shield Type Rebalance

### ISSUE THREAD

**Issue by Worldwave** [Freelancer-Sirius-Revival/FLSR#514]
![image](https://user-images.githubusercontent.com/65657072/227623760-36688007-b33a-40f2-8011-fc233420b6dd.png)

This is the new suggestion for balancing damage types on shields.
It makes it so light fighters are stronger against the shieldtype that is good against heavy fighters (Neutrino).
And heavy fighters are strong against the shield that is good against light fighters (Graviton)

And removes damage stats that gave too much of an advantages to guns that are used more for hull damage, because they just had too much going for them (Plasma and Tachyon). This makes Laser and Photon which are primarily M and L weapons good as utility addins against tricky shield types.

**Comment by Worldwave** [comment]
![image](https://user-images.githubusercontent.com/65657072/230603230-f08bab05-647c-4c71-8467-ddf7b72e9e7f.png)
Latest suggestion for rebalance

**Comment by erikroe** [comment]
Was implemented by the Milestone 12 shield rebalance.
