### ISSUE TITLE
Kusari Battleship docking points out of line

### ISSUE THREAD

**Issue by thaddeus-ex** [Freelancer-Sirius-Revival/FLSR#516]
Docking points out of line on last leg, ship noses upwards just at point of entering bay.

**Comment by thaddeus-ex** [comment]
Will correct with next revision. Model based on original with damage parts resized to 70%

**Comment by erikroe** [comment]
Has been already done by [commiut ](https://github.com/Freelancer-Sirius-Revival/FLSR/commit/85360b5868055c03c93dabaa2aa81e2c0341e9a4)
