### ISSUE TITLE
Change TLR to Badlands being partially broken

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#536]
Change TLR to Badlands being partially broken to show how much Liberty does not care what is going on there anymore. Adding some atmosphere.

**Comment by FireFlyEx** [comment]
Do we have partially broken rings, as opposed to not fully built ones?

**Comment by FireFlyEx** [comment]
If it's not too hard.. I'd like a regular tradelane model that's missing the bottom left corner entirely and the bottom right corner is broken, but everything else is fine. I'd like to have it work only in one direction.

**Comment by FireFlyEx** [comment]
Testing @Thaddeus
