### ISSUE TITLE
Change Durham to be normal border station

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#537]
Change Durham to be normal border station.

**Comment by thaddeus-ex** [comment]
Need more details. Why isnt Durham a normal border station? aside from being nowhere near a border

**Comment by erikroe** [comment]
In long past days some stations in FLSR had been redesigned just because of. And that one looks… No idea. Unfitting.

**Comment by erikroe** [comment]
Changed Durham to space_police and moved it between TLR and Jumpgate equally in distance.
