### ISSUE TITLE
Goods trader on Osiris and Toledo

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#54]
Goods trader on Osiris and Toledo.

**Comment by FireFlyEx** [comment]
Are we going for generic items available or is there some kind of lore connection?

**Comment by FireFlyEx** [comment]
Still no details...

**Comment by FireFlyEx** [comment]
Read this!

**Comment by erikroe** [comment]
Maybe @XxSARGExX has an idea what may be best sold here.

**Comment by XxSARGExX** [comment]
Toledo woill produce tons of oxygen and water, so the only thing that Toledo and the Osiris need are food rations. It could be a long distance trade route.  Both bases also needing H-Fuel and the Osiris needs Mox like any other Capship. So we could open up the generic stuff first.

on Toledo we can sell Artifacts and Alien Organissms maybe a new good that is expensiv and heavy but has a very important use for pirate central unlawfull factions.

**Comment by XxSARGExX** [comment]
My idea for the first part:

Toledo / Osiris 
- NEEDS FOOD RATIONS
- NEEDS H FUEL
- NEEDS CONSUMER GOODS
- NEEDS ENGINE COMPONENTS
- NEEDS SHIP HULL PANELS
- BUY LUXURY FOOD 

TOLEDO
- SELL ARTIFACTS
- SELL ALIEN ORGANISMS 

OSIRIS 
- NEEDS MOX FUEL
- SELLS TOXIC WASTE
