### ISSUE TITLE
Addition of Blood Dragon "Drake" Variant to the ship roaster

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#547]
![2023-03-31 23_19_44-LancerEdit](https://user-images.githubusercontent.com/24990509/229233813-79a20ed8-7576-44db-819a-8db11bcab893.png)

**Comment by thaddeus-ex** [comment]
I will upload a revised Lithium version with modeule hardpoints

**Comment by thaddeus-ex** [comment]
![blood_drake](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/17b8ad50-2893-4510-aa64-23afd512fdc9)
(unsmoothed/unwelded model)

Progress on the Blood Drake. Re-texturing almost complete. Model has been tightened up considerably especially around the cockpit area and the baydoors. Targa hoop on the cockpit now has depth and not just a double sided texture. Taill section reworked within the limits of the current LOD0 now a bit rounder. Engine Seperated from Tail. Built around the FL:HD ku_fighter01 texture with logo removed and using a dds filter to get the red colour.
