### ISSUE TITLE
Adjusting Omega-7 Miningfield Stats

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#549]
Have adjusted the Mineable Zones in Omega-7 a bit to fit more into the play style. 

Fürstenfelde  (Explosive Gas pockets should reward more)
- Increased Drop amount
- Increased Drop chance

IMG Silver Field
- Increased Drop amount
- Increased Drop chance 

IMG Copper Field
- Increased Drop chance

**Comment by erikroe** [comment]
This may be just the first of many issues regarding drop rates. There is many asteroid fields where finer adjustments may be needed too.
