### ISSUE TITLE
Glorius in Dublin is where?

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#560]
Where is the Glorius in Dublin? That base is part of the lore of the game, even outside the campaign. Was it ever destroyed? And why is there 3 broken lane rings that no real lore ever explained.
Possibly Glorious should be added back if Lore supports it and then be made dockable or maybe just an abandoned wreck - either way is good.

**Comment by thaddeus-ex** [comment]
I have heard that there is a SP rumour that the GMG GasMiner Glorious was destroyed, but surely there would be debris? also there should be wreckage of at least the destroyer Longfield

H 132634
	After the Founders Day Revolt the Bretonian government sent several \
	destroyers to quell the uprising. The miners had captured two mining \
	ships: the Endeavor and Glorious, and the destroyers immediately \
	opened fire on them. The Endeavor got hit in the reactor core and went \
	up with all hands; the Glorious fled to an asteroid field to escape. \
	The destroyers pursued Glorious into the field and right through a \
	trap that the insurgents had set. One destroyer, the Longfield, was \
	blown in half; three other destroyers suffered terrible damage and \
	heavy casualties.

Not sure why there are tradelane rings as there are no others in Dublin space and the ones present only take you to the site of the Glorious from just outside the field. Probably a SP construct to get the player in the right spot for the triggers to play.

**Comment by thaddeus-ex** [comment]
"Where is the Glorius in Dublin?"

From m06.ini

[MsnSolar]
nickname = Br05_02
system = Br05
position = -12062, 400, -24056
orientation = 0, 0, 1, 0
string_id = 216605
faction = fc_q_grp
archetype = gas_miner
base = Br05_02_Base
pilot = MSN06_Station_Glorious
loadout = gasminer
voice = glorious

interesting that it is 400 above basline

**Comment by erikroe** [comment]
> The Bretonian military response was swift and furious. Bretonian gunboats arrived shortly, and in the ensuing battle, destroyed the Endeavor and its mutineers. They pursued the Glorious across the system into a dense field, where they stumbled into a large, explosive booby trap set by the fleeing miners. One gunboat was destroyed; several were damaged.

> The Glorious played a decisive role in the Founders Day Revolt, when miners who were escaping Bretonian justice after their brutal execution of Sir Edmund Graves took it deep into the asteroid fields. It once served as a base of operations, but has since been so badly damaged that it is deemed uninhabitable.

> Did you hear, the Rheinlanders blew up that old station Glorious in Dublin? At least it was abandoned for the most part. It was always a heap of scrap metal anyway.

> There are reports of Rheinland gunships in the Dublin system. I bet it was those same bastards that blew up the Glorious. I had friends there. I hope they got out alive.

**Comment by erikroe** [comment]
I added the Glorious as asteroid miner debris model and removed those useless broken TLR rings.
