### ISSUE TITLE
Hiryu Cloud in Sigma-19 visibility issue?

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#567]
For whatever reason you can clearly see where the gas miners are at. The lights and other effects are more visible through the cloud than the miner is.

![Freelancer 2023-04-07 22-18-22-80](https://user-images.githubusercontent.com/76809959/230699438-99dcdb69-c7c1-4569-ba19-c25ddd961021.png)

**Comment by erikroe** [comment]
That's a general Freelancer rendering issue with effects from Exclusion Zones. But fixes can be made by assigning special LOD Ranges to the effects and the Gas Miners to prevent the effects and lights to show up. These Ranges should then be the same as the visibility range of that specific cloud.
