### ISSUE TITLE
Duplicate Mouse Shield

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#568]
There are two Mouse shields and they have different stats. One sells with the Ronin but a different one is available at the equipment dealer.

**Comment by erikroe** [comment]
The real bug here is that the shield you found on Kyoto are NPC only. Though yes, their namings should be corrected. I make a second issue for that.
For now I fixed that this shield is no more sold. It should not be sold ever.
