### ISSUE TITLE
Mahon Dust Cloud in Omicron Alpha

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#569]
The Mahon Dust Cloud in Omicron Alpha has an asteroid band around it and yet there are no asteroids. It's only a dust field. Should be removed.

![Freelancer 2023-04-07 22-54-50-21](https://user-images.githubusercontent.com/76809959/230700277-21f22ef4-9078-4038-9acd-7c23c8bacd72.png)

**Comment by erikroe** [comment]
This applies to Dust Fields in Sig17 and Kyushu, too, for example. But the question is if the removal of the asteroid bands is a nice solution or not.
