### ISSUE TITLE
Benitez Foundation Engine Cruise Effect

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#570]
The Benitez Foundation Engine cruise effect is too large for a small ship.

![Freelancer 2023-04-07 23-05-44-03](https://user-images.githubusercontent.com/76809959/230700712-3f5cb927-bddc-4b9d-8c65-2251356295c3.png)
![Freelancer 2023-04-07 23-05-52-16](https://user-images.githubusercontent.com/76809959/230700713-9919ed6e-f67c-4b0b-95c8-6fcb16c432ae.png)
![Freelancer 2023-04-07 23-06-01-20](https://user-images.githubusercontent.com/76809959/230700714-4845e8a0-a8e9-4285-b846-f0dc7de4929a.png)

**Comment by FireFlyEx** [comment]
Actually... the regular engine effect is also huge.

**Comment by XxSARGExX** [comment]
All engine effects are not fitting to specific ships. On borderworld fighters, the engine fits again. Kusari fighters have small engine components so theire need slim effects.

Every engine effect in vanilla fl was made for a soecific ship.
