### ISSUE TITLE
Adding / Adjusting Shipdealer on Housesystem Junker / Hogosha bases

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#590]
Unlawful starts have it realy rough atm in certain Houses

The Junker / Hogosha Bases Shipdealer needs some adjustmend. 

My idea of offering newer unlawful player a good start:

Rochester: 
- Bloodhound (Rouges)
- CSV (Junkers)
- Dagger (Outcasts)

Trafalgar:
- Bloodhound (Mollys)
- CSV (Junker)
- Legionary (Corsairs)

Kabukicho;
- CSV ( Hogosha)
- Hawk 
- "Blood Dragon" Drake (no idea what else)

Kreuzberg:
- Bloodhound (Hessians)
- CSV (Junker)
- Hawk (Unioneers / LWB / Bundschuh)

**Comment by FireFlyEx** [comment]
Sounds good. You done yet? ;P

**Comment by erikroe** [comment]
Done. However, all core system Junkers Bases come with a Pirate Fighter, Freighter, CSV. Texas comes with all 3 super light civilian fighters. And Yanagi comes with co_fighter and bw_fighter.
