### ISSUE TITLE
Molly base in Leeds

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#6]
A new Molly base behind planet Leeds.

**Comment by FireFlyEx** [comment]
I can expand the West Leeds smog cloud and asteroid field and slip a base in just outside of the vignettes and then add some new patrols and a tiny exclusion zone.

**Comment by erikroe** [comment]
We'll also have to write up some lore and need to make sure it does not add too much disturbance to new stuff as long as we do not know universally where it should go to with the universe.

**Comment by thaddeus-ex** [comment]
![2023-04-05 (2)](https://user-images.githubusercontent.com/92892138/230004646-240c1c72-e34f-4950-8a46-942b17ecb352.png)

I propose base site be in dead area south of Dublin hole and north of higher density asteroid field WestLeeds_asteroid_1. With linking patrols to Dublin Hole and London Hole. Pop zones at both the new base and Dublin Hole. Two-three new Field vignettes, south of West Leeds Smog. Base should blend in with surroundings, either _dmg model man-made base or a rock boulder type with smog asteroid texure.

Lore: shouldnt be too difficult. Base of operations for extended raids on LD-14 and Stokes noibium fields. Mollys already have heavy presence in Leeds including an all points tour from London to Manchester holes via LD14, BS York & Stoke. As the smog fields are man-made maybe a small story about how they found a forgotten derelict abandonned base in the thick smog etc. Some industry had to produce the fields afterall, so you would expect some debris from such ventures. I am surprised that there isnt more industrial debris in the Leeds system

       "A large cloud of smog that has coalesced over the centuries from the
	various industrial operations throughout Leeds. The Bretonian Police
	Authority has begun patrolling the cloud more closely after Molly
	terrorists began using the area as a staging ground for strikes
	against the LD-14 uranium processing center."

Names: (actual real) Leeds has a large ex-pat Irish commuity that occupy an area called the "Sheepscar triangle" points of which are Meanwood, Chapletown & Burmantofts with Lovell park not so far away either. So we have a choice of "at least" five.

Commodites selling: Mined Gold from Dublin and Raided Niobium from stokes field
Commodites buying: MOX fuel for Molly reasons. Pharms (Radiation Meds) to counteract the affects of where they are living - essentially a waste dump and also the usual buy/sell items water food oxygen anime etc.

**Comment by erikroe** [comment]
Good points. I am not yet sure if I want to keep the Leeds/Dublin connection forever. So for now I'd not want to count that one in for the base.
The new base also contain a ship dealer and take off one or two ships from Arranmore.

**Comment by FireFlyEx** [comment]
Looks like we have similar ideas on location. I will post some screens of what I have atm when I get home. I'm much more inclined to keep an undamaged base for this because it will be the location where they reassemble the Foxhound. My premise is that they buy the base model of the ship from a secret source and then they modify it into the ship they fly. This allows it to be available elsewhere in a different configuration.

**Comment by thaddeus-ex** [comment]
![toxic](https://user-images.githubusercontent.com/92892138/230160147-0888b539-9523-4660-8735-9d6eb9814c24.jpg)

There is no detailmap for the Toxic texture, only the dynamic asteroid texture. Using that the base looks like this, ugly. very, very not keen. Would be better as a man-made base anyway. Someone will have to come up with some believable lore as to why it would be in one piece and the authorities havent spotted it.

**Comment by FireFlyEx** [comment]
This is what I have at the moment but I'm still experimenting as well.

![rathgar1](https://user-images.githubusercontent.com/76809959/230258218-70238671-6757-4616-bd7e-21f3399e6bfb.png)
![rathgar2](https://user-images.githubusercontent.com/76809959/230258227-5ad86f84-3569-479e-b367-ca0bb95be2e7.png)
![rathgar3](https://user-images.githubusercontent.com/76809959/230258233-b4c44385-2a5d-4da6-8f79-8649a62c878f.png)

The idea I put on Discord is that this base was abandoned by the Bretonian government hundreds of years ago when they tried to clean up Leeds and failed. The Molly's found it in a radioactive zone, which made it perfect cover for a hidden base. Bretonia knew it still existed but ignored it because it was an abandoned pos.

**Comment by thaddeus-ex** [comment]
That should work as a concept

**Comment by erikroe** [comment]
I like that one actually quite good!

**Comment by FireFlyEx** [comment]
Need to get some smoke plumes out of the exhaust pipes and some base lights for it. It's currently really well hidden but I need to increase the size of the interference zone.

**Comment by erikroe** [comment]
Should be fine to increase it

**Comment by FireFlyEx** [comment]
Need opinions. First 2 use the gas miner exhaust. Last one uses mining platform exhausts. Which is better?

![Freelancer 2023-04-09 01-39-24-20](https://user-images.githubusercontent.com/76809959/230757794-5a6dcb6b-9a38-40af-9a37-1a38409227f0.png)
![Freelancer 2023-04-09 01-42-09-48](https://user-images.githubusercontent.com/76809959/230757796-336f08e6-a6b0-4616-9142-9e82994c3655.png)
![Freelancer 2023-04-09 02-16-20-38](https://user-images.githubusercontent.com/76809959/230757799-5cb71ee2-a5e8-4f7c-b346-e83a6574d66c.png)

**Comment by erikroe** [comment]
For a fabrication station, the last one is really good. Also fits very well to the smoke cloud of Leeds.

**Comment by thaddeus-ex** [comment]
quite like the 1st one as an effect but the colours would need changing. I thought the idea was a former reprocessing plant - sucking in sulphur dioxide & hydrogen sulfide and pumping out - not sure. water? gypsum? as its a shipbuilding facility would the processing equipment be in use anyway? looking good anyway. that is quite high radiation there
