### ISSUE TITLE
Correct interior doors on Space_port_dmg Add new models Space_port01 & Space_port_dock

### ISSUE THREAD

**Issue by thaddeus-ex** [Freelancer-Sirius-Revival/FLSR#601]
![space_port_dmg](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/68b09321-414e-4d86-a78e-c556f47e461b)
Space_port_dmg interior upper doors badly skinned, correct and re-export

Add re-textured non-damaged version as civilian space_port model
![screen52](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/c316ba13-b1ee-4e5a-b826-fe3d55457230)
testing at Rochester

Create single dock module from the re-textured non-damaged version as civilian space_port model
![space_port_dock](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/467e76ae-63ac-4a0c-ac96-732a02d63f2d)

**Comment by thaddeus-ex** [comment]
Visible modelling completed, SUR creation in progress. Considering new SUR model for space_port_dmg as original is rather basic and will be shared with space_port01.

**Comment by FireFlyEx** [comment]
> Create single dock module from the re-textured non-damaged version as civilian space_port model ![space_port_dock](https://user-images.githubusercontent.com/92892138/238123515-467e76ae-63ac-4a0c-ac96-732a02d63f2d.jpg)

Was the model always asymmetric?

**Comment by thaddeus-ex** [comment]
space_port_dmg ~ doors corrected. from fitted sur added.
space_port01 ~ numbered doors - same spec as above _dmg model with form fitting sur
space_port_dock ~ standalone dock module, non-numbered doors, form fitting sur
SOLAR\loadouts.ini & SOLAR\solararch.ini update for new entries and default loadouts _dock model has one runninglight less than the other two.
