### ISSUE TITLE
Delete Leeds Jumphole in Dublin

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#602]
The Leeds Jumphole in Dublin or the Dublin Jumphole in Leeds should be deleted. 

Like any other story jumphole, it also has no patrol paths and the dublin coutnerpart in leeds is way to close to the tradelane. 

![2023-05-13 12_36_47-Freelancer](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/0395754b-9354-4325-b00c-202d564b5122)
![2023-05-13 12_37_10-Freelancer](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/da82db26-f9e7-49ed-94d6-de7613aeeb59)

**Comment by FireFlyEx** [comment]
You either delete both or you leave both. You can't just keep one.

**Comment by XxSARGExX** [comment]
i know :), question was bad asked ^^
