### ISSUE TITLE
Differentiate FIGHTER and FREIGHTER player ships for NPC Pilots

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#616]
NPC pilots go on FIGHTER and FREIGHTER for differentiating between different player ship types.
For that to work, player ships must be redefined and basically all ships that are not capital ships must be of FIGHTER class for players.

**Comment by FireFlyEx** [comment]
If only there was a way to get the other types to actually work correctly..
