### ISSUE TITLE
FLSpew Sound Bugs

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#621]
E:\FL\Scratch\Source\Client\cmn\Sound.cpp(1242) : *** WARNING: sound reference count leaks detected: 1 sounds
E:\FL\Scratch\Source\Client\cmn\SoundArch.cpp(457) : *** WARNING: sound "audio\sounds\equipment\drill_ore.wav" has attenuation out of valid range (0, -96)

**Comment by erikroe** [comment]
`sound reference count leaks detected` seems to be known issue that does not

**Comment by Dvurechensky** [comment]
Вам необходимо откорректировать Attenuation и пробить число -96  по своему проекту и по файлу wav.
