### ISSUE TITLE
Leeds Exclusion Zones broken

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#623]
get_zone(ZONE_Br04_EastLeeds_exclusion_1) failed
E:\FL\Scratch\Source\Client\Space\Nebula.cpp(690) : *** ERROR: AsteroidField linked to missing Exclusion Zone (ZONE_Br04_EastLeeds_exclusion_1)
E:\FL\Scratch\Source\Common\Systems.cpp(3228) : *** WARNING: get_zone(ZONE_Br04_EastLeeds_exclusion_2) failed
E:\FL\Scratch\Source\Client\Space\Nebula.cpp(690) : *** ERROR: AsteroidField linked to missing Exclusion Zone (ZONE_Br04_EastLeeds_exclusion_2)
E:\FL\Scratch\Source\Common\Systems.cpp(3228) : *** WARNING: get_zone(ZONE_Br04_EastLeeds_exclusion_3) failed
E:\FL\Scratch\Source\Client\Space\Nebula.cpp(690) : *** ERROR: AsteroidField linked to missing Exclusion Zone (ZONE_Br04_EastLeeds_exclusion_3)
E:\FL\Scratch\Source\Common\Systems.cpp(3228) : *** WARNING: get_zone(ZONE_Br04_EastLeeds_exclusion_4) failed
E:\FL\Scratch\Source\Client\Space\Nebula.cpp(690) : *** ERROR: AsteroidField linked to missing Exclusion Zone (ZONE_Br04_EastLeeds_exclusion_4)

**Comment by thaddeus-ex** [comment]
are these removed zones ghosting in the player files?

**Comment by XxSARGExX** [comment]
I added a exclusion zone for the mineable niob asteroids but on my side i never deleted something
