### ISSUE TITLE
Maghera (?) missing bar background prop errors

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#624]
E:\FL\Scratch\Source\Client\Gf\ObjectProp.cpp(105) : *** ERROR: No valid archetype for prop $terrain_tiny

And more of that type with different variables that are not served.

**Comment by FireFlyEx** [comment]
Notes to self... this 'prop' is found in the following files:
```
scripts\bases\Ambi_Terrain_Static_D01.thn
scripts\bases\Ambi_Terrain_Static_D02.thn
```
