### ISSUE TITLE
Texture verify failed

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#627]
C:\work\builds\dalibs\DALIBS~1\build\include\IMaterialImpl.h(575) : NOTICE:General:texture verify failed: mv_vidmaterial: vidmaterial.tga

**Comment by FireFlyEx** [comment]
That texture is only in one file: DATA\Interface\NeuroNet\MissionVendor\mv_videoscreen.3db

**Comment by FireFlyEx** [comment]
In HDE they 'fixed' this error by deleting the Texture library node and the Dt_name and Dt_flags nodes under MV_vidmaterial.

**Comment by erikroe** [comment]
Took the HDE variant. Thanks!
