### ISSUE TITLE
Constant RenderPipeline Warnings for Thaddeus

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#632]
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3020) : WARNING:General:set_material() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3687) : WARNING:General:set_texture_stage_texture() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3640) : WARNING:General:set_texture_stage_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3586) : WARNING:General:set_render_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3586) : WARNING:General:set_render_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3586) : WARNING:General:set_render_state() called outside of create_buffers/destroy_buffers
C:\work\builds\dalibs\dalibs-build\build\Src\RenderPipeline\DX8\rp_dx8.cpp(3717) : WARNING:General:verify_state() called outside of create_buffers/destroy_buffers

**Comment by thaddeus-ex** [comment]
these warnings are usally caused be me tabbing to desktop while docking at bases or in jump tunnels between systems, never had a ctd with these.

**Comment by erikroe** [comment]
Good to know. Then I close it as "can be ignored".
