### ISSUE TITLE
Missing Hardpoint Warnings Serverside

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#633]
E:\FL\Scratch\Source\Common\CExternalEquip.cpp(142) : *** WARNING: CExternalEquip: Object (0x90fff744) missing hardpoint (HpThruster01) for item (0x89f85540)
E:\FL\Scratch\Source\Common\CExternalEquip.cpp(142) : *** WARNING: CExternalEquip: Object (0xa7405cc1) missing hardpoint (HpWeapon03) for item (0x86973601)
E:\FL\Scratch\Source\Common\CExternalEquip.cpp(142) : *** WARNING: CExternalEquip: Object (0xa7405cc1) missing hardpoint (HpRunningLight01) for item (0xa6f3fbc9)
E:\FL\Scratch\Source\Common\CExternalEquip.cpp(142) : *** WARNING: CExternalEquip: Object (0xa7405cc1) missing hardpoint (HpRunningLight03) for item (0xa6f3fbc9)
E:\FL\Scratch\Source\Common\CExternalEquip.cpp(142) : *** WARNING: CExternalEquip: Object (0xa7405cc1) missing hardpoint (HpContrail02) for item (0x950ecf44)

**Comment by FireFlyEx** [comment]
0x89f85540 = ge_s_thruster_01
0x86973601 = fc_c_gun_neutron_heavy01
0xa6f3fbc9 = SlowSmallPurple
0x950ecf44 = contrail01

**Comment by FireFlyEx** [comment]
0x90fff744 = co_ship_fighter_light01_npc
0xa7405cc1 = co_elite2

**Comment by thaddeus-ex** [comment]
0x86973601 = fc_c_gun_neutron_heavy01
0xa6f3fbc9 = SlowSmallPurple
0x950ecf44 = contrail01

these are all assigned port_wing on the pi_vheavy model. I cant see anything wrong with the model.

**Comment by thaddeus-ex** [comment]
used to be a problem with very early ms3d exporters - didnt write multiple part cmps properly and the game didnt recognise that a part had been destroyed, kept trying to spawn the equipment on that part. running/dock light and contrail warnings only though, guns were destroyed. I dont think that is happening here, something else.

**Comment by erikroe** [comment]
Was fixed for the Corsair Fighter. The others may have been exceptions of some sort. I'll close this here and see if it happens again in the future.
