### ISSUE TITLE
Rumours for Maghera Base

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#635]
Maghera Base currently has rumours of Arranmore. It should have its own set.

**Comment by Caenen** [comment]
I added a bunch of original rumors to fill the base with life: 
[Maghera base rumors June 2023.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/11629100/Maghera.base.rumors.June.2023.zip)

**Comment by erikroe** [comment]
Corrected and commited. Thanks!
