### ISSUE TITLE
mBases rumorknowdb for all existing modded rumors

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#650]
I went through all the new rumors the mod added to mBases.ini in the past and gave them the relevant station, wreck or nebula reveals on the navmap. I also fixed some errors.
[Rumors knowdb additions june 2023.zip](https://github.com/Freelancer-Sirius-Revival/FLSR/files/11634692/Rumors.knowdb.additions.june.2023.zip)

**Comment by erikroe** [comment]
Added it, thanks.
