### ISSUE TITLE
ci_plasma_01 Effects missing

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#658]
> E:\FL\Scratch\Source\Client\space\Effect.cpp(1003) : *** ERROR: could not find alchemy effect (ci_plasma_01_flash) in file (fx\weapons\ci_plasma_01.ale)
> E:\FL\Scratch\Source\Client\space\Effect.cpp(1003) : *** ERROR: could not find alchemy effect (ci_plasma_01_proj) in file (fx\weapons\ci_plasma_01.ale)
> E:\FL\Scratch\Source\Client\space\Effect.cpp(1003) : *** ERROR: could not find alchemy effect (ci_plasma_01_proj) in file (fx\weapons\ci_plasma_01.ale)
> E:\FL\Scratch\Source\Client\space\Effect.cpp(1003) : *** ERROR: could not find alchemy effect (ci_plasma_01_impact) in file (fx\weapons\ci_plasma_01.ale)
> E:\FL\Scratch\Source\Client\cmn\ALELib.cpp(92) : *** ERROR: Failed to load fx\weapons\ci_plasma_01.ale.

**Comment by thaddeus-ex** [comment]
ci_plasma_01.ale not present in folder - fx\weapons\

**Comment by XxSARGExX** [comment]
actualy it was made by worldwave in the first place
