### ISSUE TITLE
Pirate Elite fighter 

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#68]
A pirate elite fighter from Thaddeus' mod. CO_Elite3
Rework:
Bloodhound
Armor: 5000
Cargo: 100
Weapons: 4 (3L / 1M)
Bots/Bats : 5/10 

Foxhound 
Armor: 6000 
Cargo: 30
Weapons: 6 (2L / 2M / 2H)
Bots/Bats : 4/8 

Wolfhound 
Armor: 8000
Cargo: 200
Weapons: 5 (3M/2H)
Bots/Bats : 5/10

**Comment by FireFlyEx** [comment]
What are you wanting done here?

**Comment by erikroe** [comment]
@thaddeus-ex Normals of this ship will need  improvement. There's a bunch of oddly lit surfaces.

**Comment by thaddeus-ex** [comment]
There are a couple of things that need improvement
