### ISSUE TITLE
Add "Mines Detected" warning sooner before encountering mine fields

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#683]
This could be done with new fields on top of the dense/insta-kill minefields that are slightly bigger, tagged as mine field and empty (so that the "Mines Detected" warning occurs when coming close to a dense mine field, rather than only when you enter the passages)

**Comment by erikroe** [comment]
The update of the asteroids also increased visibility range for mines. Perhaps this issue may be solved by this.

**Comment by Caenen** [comment]
Problematic are those in nebulae in particular, which I dont think the LOD range change will have an effect on. Investigating.
