### ISSUE TITLE
Esperanza docking denied in unlawful start

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#686]
Known bug but missing an issue thus far - Sometimes, but not consistently, the game thinks you aren't allowed to dock back with Esperanza. The voice line it prompts is "Access Denied" (while rep requirement not being met in Hook's check prompty "Access Denied, Destination Hostile" instead).

It is unknown what triggers this and what allows docking again. I have not experimented in the character creation screen or in any other place. It is unclear whether the client thinks that the object is marked as not allowed to dock or FLHook prevents the docking in some other way.

**Comment by erikroe** [comment]
See https://github.com/Freelancer-Sirius-Revival/FLSR-Hook/issues/11

**Comment by Caenen** [comment]
### Addendum

This bug was found to be the result of a Vanilla Freelancer behaviour:
At runtime, the server keeps some list of objects (bases, gates) that are undockable to players, initially populated by (allegedly) initialworld.ini. If a character connects with a save file that has an object listed as undockable that the server does not have in this list, then the object is added to it. When any new character connects, the server will not let them dock with that object. When the character leaves, the undockable object entry is added to their save file as well.

Because of this, when a base or gate is made dockable (like Esperanza was), in addition to removing the entry in the initialworld.ini, all safe files must be culled of the entry.
