### ISSUE TITLE
Nomad Defender target mesh missing

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#688]
Need someone to confirm this isn't just a local issue on my end, but out of all ships the Nomad Defender gunship exclusively is missing its mesh when I target it.
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/0be92fc4-a25a-4518-8e94-3820c16ef0e7)

**Comment by erikroe** [comment]
That's correct. TW didn't rework all his ships yet for them.

**Comment by thaddeus-ex** [comment]
Most of trees Nomad Capitals dont have wireframes. They are single part, single LOD models. It makes them quite complicated and time consuming to make a wireframe for - especially as the interior form is not a seperate part as in the other vanilla models. Seperating it all is a nightmare. I'll do the defender as it is quite a common ship but I dont like to tread on others toes if the models are in active developement
