### ISSUE TITLE
Cannot navigate from Bar room to ship dealer on Ames Research Station

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#689]
The ship dealer is an addition by the mod and this room was missed from adding it in completely.

**Comment by erikroe** [comment]
Should be checked for every other Freeport that has a shipdealer added.

**Comment by Caenen** [comment]
I just checked the rooms on all the freeports and none other than Ames' bar have the bug. I did not notice it anywhere but on Ames while playing, either. I'll keep my eyes open but will close this particular issue after resolving Ames.
