### ISSUE TITLE
Asteroid and Gas mining by stationary objects

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#7]
Inspired by Nomad Legacy asteroid and gas mining could be done with stationary objects. Asteroids specifically could be made in layers that must be destroyed first to get to the actual resources.

**Comment by XxSARGExX** [comment]
Current Mining locations: 

Gas:
- Sigma -13 
- Sigma - 7 
- Sigma - 43
- New London
- Leeds
- Tau-29
- Omega - 7
- Omega - 3
- Omega - 41
- Alaska
- Tohoku
- Texas
- Honshu
- Kepler


Asteroids
- Omega - 7
- Tau - 31
- Tau - 23
- Dresden
- Tau - 37
- Leeds
- Dublin
- Manchester
- Magellan
- Cortez
- Omega - 3

I am done placing mineable by 70%, just need to polish some effects and utilize all the assets we have now at our disposal

**Comment by erikroe** [comment]
@XxSARGExX Is this issue finished?
