### ISSUE TITLE
Tau-23 field Increased Drag?

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#706]
~~Since release 2023.12,~~ The ``drag_modifier = 1.05`` in the Tau-23 asteroid field is active. In-game you will hear the "Increased drag detected" warning* and your speed and acceleration/deceleration are very slightly decreased. I have not tested if this effect still scales with the interference factor or is separate from it.

~~What has caused this Vanilla argument to start working this patch all of the sudden (did we add some exe hack that included the re-enabling of the feature)?~~ Do we remove the effect in this system or keep it? Are there any other nebulae or fields in the game right now where increased drag would be useful to gameplay?

*See later comment

**Comment by erikroe** [comment]
I never noticed and I cannot remember I ever re-activated the feature.

**Comment by Caenen** [comment]
Normally, you will never get the UI audio message for the drag modifier, since the 0.03 radiation damage triggers the radiation damage warning message instead. However, if you tab into the game while undocking, you can get the 'increased drag detected' message, just like you can get the "shield deactivated" message if you tab into the game while in the docking cutscene. This initially confused me into thinking some chage in 2023.12 reactivated the feature, but it was most likely present for longer than that already.

The drag modifier set in the Tau-23 zone reduces engine and engine + thruster speeds by 5% (to ~76 and ~190, respectively) but does not affect a ship's cruise engine speed. There exists a hack to do so if we ever needed it to work with zone drag modifiers:
> 74 -> EB    common.dll    053796    adoxa    Adjust cruise speed according to drag_modifier.

For now, I see no reason to do anything with this feature, nor do I see a specific reason to remove the drag modifier from Tau-23 since it stems from vanilla originally and causes no problems of any kind so far.

**Comment by Caenen** [comment]
As a minor idea, a drag modifier <1 could be used on a race track region to design something unique, but until I am implementing anything concrete towards racing, I'll just note this here to possibly come back to it later.

**Comment by erikroe** [comment]
I suggest to remove the Drag in the Taus and be done with this for now.

**Comment by Caenen** [comment]
I rule to keep it as vanilla for now, and just have this issue in mind as documentation if we ever do something with drag in the future.
