### ISSUE TITLE
Wrecks drop their cargo hold every time they are looted by the same character, only their mounted equipment is dropped only once per char

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#715]
Already mentioned this a while back - good examples are Pathfinder (Opt. Power Heavy is in cargo) and Honshu Maru (2x Silver Fire (X) and its Vanilla Alien Organisms are in cargo), where those can be looted multiple times.

Test if internal equip underlies the same rules as external mounted weapons, and fix this for all wrecks when rebalancing/redistributing wrecks/items on wrecks is an active topic again.

**Comment by thaddeus-ex** [comment]
The Omicron Beta wrecks EW02 (Pathfinder, Hosho Maru & Escorts)  have a different flag "visit = 0" that enables the wreck to be looted multiple-infinite times. Normal flag is "visit = 16" - loot once per character only. Pretty sure this behaviour is only in Ew02. I have been looting the Pathfinder for years, more feature than a bug. Enables players to access class10 weapons even if they have looted every other wreck in the game.
