### ISSUE TITLE
Upscale Rheinland Battleship debris models in Sigma-13

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#726]
Upscale Rheinland Battleship debris models in Sigma-13. They do currently not match the RH Battleship's size. And never did match them in vanilla FL, too.

**Comment by thaddeus-ex** [comment]
The battleship front section roughly conforms to the 0.7 scaled model currently use in FLSR. If anything it appears to be compressed & stretched. in places

![rh_battleship_dmg](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/bc426a33-21ef-486f-a0df-8e6d023e4cf8)

**Comment by erikroe** [comment]
Thanks for checking.
