### ISSUE TITLE
Obscure missing or flipped surfaces on Liner model

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#792]
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/e5fc756a-a580-46d3-a35c-b98eec2924d3)
![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/3a12ef22-0394-4e2f-a815-6a87f91cfdcf)

Discovered on Prison Liner, might also affect Luxury Liner. Fairly minor issue in of itself.

**Comment by thaddeus-ex** [comment]
lower sill on bottom windows completely missing on section - starboard side "prison_frnt" lod0. remedy import same section from luxury liner and swap like for like.

**Comment by thaddeus-ex** [comment]
![2024-03-31](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/92892138/6a2c71b6-6676-4205-82bc-80db04d19f25)
