### ISSUE TITLE
Ingredients stays in cargo after crafting

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#793]
I have noticed a bug while crafting Commodities on bases. 

The ingredients stay in my cargo hold on all recipes i have encountered so far

- Polymers
- Optical Chips
- Basic Alloys
and a few more. 

Images below shoe me trying to conver CO2 into Terraforming gases

i use **/craft CO2 - Terra Forming Gases 250** 

The cargohold check is working i could not convert 500 CO2 into 1000 Terraforming Gases.
The Item Type check seems to work too.

But due to the fact that the ingredients stays in the hold, you have more cargo than you can carry (Example with a small transport)

![2024-03-29 18_51_33-Freelancer](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/630706e1-dc74-4ce2-b58c-09f283ee316d)
![2024-03-29 18_51_50-Freelancer](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/fc74373e-4ad3-43f0-b82e-d5e686d6c7e7)
![2024-03-29 18_52_09-D__Daten_Modding_Freelancer_Modding_EXE_flhook_plugins_FLSR-Crafting cfg - Notep](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/1b5bc6da-ba3b-4bc6-a3e1-38512804dc94)

**Comment by erikroe** [comment]
Fixed in Server Hook.
