### ISSUE TITLE
Group member display on Navmap can stop working under some circumstance

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#816]
The new improvements to the display of group members on the navmap is awesome and I have already used it to e.g. see where the carrier player I am docked with is going alongside additional escort players.

Around the same time I noticed this bug where the display would entirely stop due to some condition until that condition was no longer met. Another group member docked with the carrier at around the same time the group jumped to another system. Right after that the feature stopped working for all group members. When I noticed the feature working again, nobody was docked in the carrier system anymore AND the carrier had just disconnected as well.

I can currently only guess for the condition. To be tested are:
1. A group member (client order may be relevant, in that case a group member with the lowest ID) is in a system with visit flag 128 (unlisted), such as the Carrier system or Ew05/06
2. The feature cannot properly display group members ACROSS systems, and only places group markers into the system of the "first" group member for group members in that system or until it iterates to a group member not in that system.

![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/de9b4236-fb84-4e3d-83bc-9a6663aafc58)

**Comment by erikroe** [comment]
BC found the issue:

> The devs forgot to do another pointer++ in the same while loop 🥲 
Undo the 08DC07 patch and apply these:
```
Freelancer.exe, 08D89B, 90 90 90 90 90 -> 83 C5 18 EB 50
Freelancer.exe, 08D997, 55 -> 00
```
