### ISSUE TITLE
Ejecting cargo from the spectator ship crashes the server

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#824]
The spectator ship (``admin_ship_invisible01``) is very bare-bones and doesn't have a cargo hatch. Something about this causes the server to crash when a player attempts to jettison items from their cargo hold while in space. 

Since this can happen in natural settings during events for example if the admin player forgets about this, we should fix this eventually.

**Comment by erikroe** [comment]
If the problem is Baydoor HPs being not the same for start and end, then it also must be fixed for the Nomad capships/fighters.

**Comment by erikroe** [comment]
Fixed.
