### ISSUE TITLE
Codenames dropable as Blueprints

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#869]
Codenames are currently just obtainable through wreckages and only ones per character, this should be changed by dropping Blueprints instead of the item directly. 

Visit-Flags will be set to all new chars meaning that we can keep the guns as a "display" on the wreckages but you only get the Blueprint from its cargo (cargo will be dropped anytime). 

furthermore, Codenames must be crafted by getting MKII weapons first and some additional high-value Commodities.

**Comment by Caenen** [comment]
> Visit-Flags will be set to all new chars meaning that we can keep the guns as a "display" on the wreckages

We could also adjust the SURPISE_drop_cargo fuse for this goal (specifically, create an alterative variant of it which makes the hardpoint equip fates to be debris). I suspect that may be a simpler solution in the long run.

> Codenames must be crafted by getting MKII weapons first

Not sure on this, we might want to discuss this a little closer in the dev-topic

**Comment by erikroe** [comment]
@XxSARGExX what's the progress here? Is this done for everything now? If yes, please close the issue.
