### ISSUE TITLE
Equipment Crafting Bug

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#870]
![2024-07-04 21_29_40-Freelancer](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/24990509/ef10035a-01bf-4dfe-bd24-b89b52ae3ef8)

I noticed a bug in terms of crafting multiple amounts of equipment. 

If your blueprint or recipe requires equipment itself, it will only delete one item out of your cargohold if you craft the same recipe multiple times 

like in the image above i have succesfully crafted 3x ONIX out of 3x Novablast but only one was deleted

**Comment by erikroe** [comment]
Fixed.
