### ISSUE TITLE
IFF should not consider being shot by negative damage (Repair guns) an "attack"

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#877]
As noticed in 5th of July's play-together event, repair guns still counting as a normal attack leads to confusing situations in-game.

The check for damage type that the trigger to set another player hostile if they attack a non-friendly target is already using should additionally check whether the damage is greater or equal to 0 (zero-damage hits should still be considered an attack, even if currently there is no important example for a 0-damage hit besides some pulse or EMP guns on hull).

Note: check if dealing negative damage to a full-health target/component keeps it original damage amount or is reduced to the HP it can un-undo (becomes a 0 damage hit)?

**Comment by erikroe** [comment]
This cannot be solved currently. FLHook 2 allows not to track the actual damage caused. The reason is similar why sometimes even the wrong player gets attributed for damaging someone.

**Comment by erikroe** [comment]
Implemented. @Caenen can you verify it on the test server? For me it worked.
