### ISSUE TITLE
Death messages are no longer explicit about cause of death, and players killing another player are not properly rewarded 50% of their death penalty

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#886]
Might be something that broke from re-doing all the .exe hacks and what not. I am unfamiliar with what managed this before, I suspect both things in the issue title will have the same root cause though.

**Comment by erikroe** [comment]
Apparently some enum I added didn't want to behave as I wanted. I could not find out why, so I reverted the change that causes the issue.
