### ISSUE TITLE
Automatic hostile IFF from being hit by another player must not trigger in the Antartica system

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#887]
Currently there is a bug that allows PVP damage to happen in the Antarctica system (See https://github.com/Freelancer-Sirius-Revival/FLSR/issues/886). Once that bug is resolved, it must be checked whether this feature still triggers in the Antarctica system, which only serves to be confusing to new players in that particular case.

May be combinable with https://github.com/Freelancer-Sirius-Revival/FLSR/issues/877, which regards negative and 0 damage hits in general.

**Comment by erikroe** [comment]
Added No PVP system check based on FLHook.ini entries.
