### ISSUE TITLE
Misplaced collision surface on Br_Destroyer back L turrets

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#894]
Noticed this while playing today.
![grafik](https://github.com/user-attachments/assets/cae2b1c2-4746-4cab-9efd-e05e929cb8c6)

Checked LancerEdit to check out why:
![grafik](https://github.com/user-attachments/assets/e6aca3ca-f120-498c-b829-616a1f4215bb)

Which location is the intended for the turrets? Does the Sur need to be adjusted or the hardpoints?

**Comment by thaddeus-ex** [comment]
![2024-09-05](https://github.com/user-attachments/assets/cfdd120a-d22d-469b-be86-bb26090d2781)

youre right, they dont match. odd. this sur was done with maxlancer. shouldnt be a discrepancy, turret point must have been from an earlier model grafted in with xml. Was thinking of updating this anyway with turret pads, same as the old disco model and incorporate the lower side points as well.

**Comment by thaddeus-ex** [comment]
![2024-09-05 (1)](https://github.com/user-attachments/assets/1fd334ff-61f0-42a0-a746-e739d02067ee)

sur corrections for revision01c. Other equipment collision surfaces updated and resized.
