### ISSUE TITLE
Some guns are too loud (Codenames) 01

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#919]
Following reported guns have to loud Sound effects:

- ATRAX
- REVENANT 
- GLORY

**Comment by Worldwave** [comment]
Since the sounds were meant to be reused if needed, instead of changing attenuation value in the ini, let me reexport the sounds at a lower level. easier to reuse them in the project for other weapons that way, we don't have to remember specific attenuation values.

**Comment by Caenen** [comment]
Created https://github.com/Freelancer-Sirius-Revival/FLSR/tree/firesound-loudness-corrections with Worldwave, but this isn't tested in-game yet and I have not created a list of guns affected by the attenuation change. The sound definitions are also duplicated, I did not deduplicate them for now as I did not complete investigating the extend here.

**Comment by erikroe** [comment]
I fixed it by mixing the sounds down to mono.
