### ISSUE TITLE
Enhancing Glacial Beasts Loadouts

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#936]
For future Seasonal Events, Beasts (and Winter Wardens) will get more enhanced Loadouts so we can use them as "event" Npc´s with special loot on board

**Comment by Caenen** [comment]
Are the guns themselves lootable? Are they intended to be reskins of existing guns or something else?

**Comment by XxSARGExX** [comment]
> Are the guns themselves lootable? Are they intended to be reskins of existing guns or something else?

yes, like any other gund there is a small drop chance
