### ISSUE TITLE
Corsairs in Edinburgh (Br06)

### ISSUE THREAD

**Issue by Caenen** [Freelancer-Sirius-Revival/FLSR#964]
Corsairs (somehow) have presence in the Edinburgh System since Vanilla. I can only speculate this is to make the system less empty. However, it makes absolutely 0 sense as they do not traverse Leeds, there is no connection to Dublin, Cambridge or any other system, notwithstanding that IF there was a connection from either Dublin or New London, Mollys would almost certainly show up there too.

The Outcasts in the Edinburgh only pass through, leaving the Gaians as the sole "unlawful" faction of the system. There is no reasonable replacement for a second area faction in this corner of space unless we create one.

Suggestion is to remove the Corsairs from the system and replace them with nothing, just leave Gaians.

**Comment by erikroe** [comment]
Yes, please remove them.
