### ISSUE TITLE
DESTROYABLE_DEPOT Type ignores empathy rate settings

### ISSUE THREAD

**Issue by XxSARGExX** [Freelancer-Sirius-Revival/FLSR#975]
During my testing find some odd behaviour on Depots. 

Solars with 
**type = DESTROYABLE_DEPOT**

seems to ignore the empathy rates, if i destroy a Depot container i get -0.1 Reputation even if the object destruction rate is set to 0. Killing ships or weapon platforms are not a problem. 

My test:

Winter Wardens (All Empathy rate setting 0, You never should lose Reputation):
- Set Reputation to 0.9 
- Destroyed a Ship, Reputation still 0.9
- Destroyed a Transport, Reputation still 0.9 
- Destroyed a Weapons Platform, Reputation still 0.9
- Destroyed a Depot Container, Reputation down to 0.8 

BMM:
- Set Reputation to 0.9
- Destroyed a Ship, Reputation down to 0.85
- Set Reputation back to 0.9
- Destroyed a Transport, Reputation down to 0.85
- Set Reputation back to 0.9 
- Destroyed a Depot Container, Reputation down to 0.8

**Comment by XxSARGExX** [comment]
According to @BC46 

The Behaviour of destroying Solars of the type **DESTROYABLE_DEPOT** is indeed hardocded. 
You will lose a fix amount of reputation with the owner of the depot object (destroying parts of it) 

BC46 found the offset for it here:
content.dll, D00D4, -0.1f = reputation lost after destroying DESTROYABLE_DEPOT solar

**Comment by erikroe** [comment]
I have changed it to -0.05 to match our usual empathy settings.
