### ISSUE TITLE
Voice message 2351700488 is invalid for voice 3073825485

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#98]
*** WARNING: Voice message 2351700488 is invalid for voice 3073825485
*** WARNING: Voice message 2353493514 is invalid for voice 3073825485

**Comment by FireFlyEx** [comment]
2351700488 is dock_granted
2353493514 is FreeFlight

These sounds do not exist in nnvoice.utf and that's why it throws this error. There are other known sounds that are missing and I am currently cleaning up an old fix for these and many other voice errors.

**Comment by erikroe** [comment]
Good hint. I synchronised it with FLHDE now.
